### ISSUE TITLE
Is it correct finalizing of the program?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#103]
I run
kw13919:litvina~/NEWMIMCLIB/mimclib_1June2017/tests/CEM> python run.py -mimc_TOL 0.001 -mimc_max_TOL 0.5  -mimc_min_dim 1 -qoi_seed 0     -mimc_theta 0.5 -mimc_M0 15 -mimc_h0inv 3     -mimc_w 2 -mimc_s 4 -mimc_gamma 2 -mimc_beta 2     -mimc_bayes_fit_lvls 3 -mimc_moments 4     -mimc_bayesian True -mimc_reuse_samples False  -mimc_verbose 10 -db True

and receive
BLA_BLA_BLA
Time for post-processing:::      1.51944518
---------------------------------------------------------- 
Data Structures are being removed! ...
DONE... Data Structures are removed! ...
---------------------------------------------------------- 
Flag SFieldEndRuns 
Flag SFieldDestroy 

Traceback (most recent call last):
  File "run.py", line 75, in <module>
    fnAddExtraArgs=None, fnSeed=seedRandomGen)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/test.py", line 104, in RunStandardTest
    mimcRun.doRun()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/mimc.py", line 859, in doRun
    samples_added = self._genSamples(newTodoM) or samples_added
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/mimc.py", line 775, in _genSamples
    self.all_itr.addSamples(i, *args)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/mimc.py", line 226, in addSamples
    if self.M[lvl_idx] == 0:
IndexError: index 0 is out of bounds for axis 0 with size 0
kw13919:litvina~/NEWMIMCLIB/mimclib_1June2017/tests/CEM> 

??? should it be like this?

**Comment by haji-ali** [comment]
Can you use the code tag when posting. It's somewhat difficult to read your output.
Anyways, no. The program shouldn't terminate like that. I am not sure what the error is though. 

If you are still experiencing this issue, I need more info

**Comment by litvinen** [comment]
Which exactly additional information is necessary? 
run.py? 
my ./echo_cmd.py?
