### ISSUE TITLE
Problem with lev2knots_doubling method in the misc code

### ISSUE THREAD

**Issue by hammouc** [StochasticNumerics/mimclib#111]
I am using the following definition of extendLvls method  in my mimc_run script and I always get the below error due to the definition of lev2knots_doubling method in misc code.

`def extendLvls(self, run, lvls):

        if len(lvls) == 0:

            d = run.params.min_dim + self.extrapolate_s_dims

            eye = np.eye(d, dtype=int)

            new_lvls = np.vstack([np.zeros(d, dtype=int)] +
                             [i*eye for i in range(1, run.params.min_lvls)])
            lvls.add_from_list(new_lvls)

            return

        import time

        tStart = time.time()

        # estimate rates

        self.d_err_rates, \

            s_fit_rates = misc.estimate_misc_error_rates(d=run.params.min_dim,
                                                         lvls=lvls,
                                                         errs=run.last_itr.calcDeltaEl(),
                                                         d_err_rates=self.d_err_rates,
                                                         lev2knots=lambda beta:misc.lev2knots_doubling(beta+1))

        #################### extrapolate error rates

        if s_fit_rates is not None:
            valid = np.nonzero(s_fit_rates > 1e-15)[0]  # rates that are negative or close to zero are not accurate.
            N = len(s_fit_rates) + self.extrapolate_s_dims
            k_of_N = self.transNK(1, N)
            K = np.max(k_of_N)
            c = np.polyfit(np.log(1+k_of_N[valid]), s_fit_rates[valid], 1)
            k_rates_stoch = c[0]*np.log(1+np.arange(0, K+1)) + c[1]
            s_err_rates = np.maximum(k_rates_stoch[k_of_N[:N]],
                                     np.min(s_fit_rates[valid]))
            s_err_rates[valid] = s_fit_rates[valid]  # The fitted rates should remain the same
        else:
            s_err_rates = []
        tEnd_rates = time.time() - tStart
        ######### Update
        tStart = time.time()
        self.profCalc = setutil.MISCProfCalculator(self.d_err_rates +
                                                   self.d_work_rates,
                                                   s_err_rates)
        mimc.extend_prof_lvls(lvls, self.profCalc, run.params.min_lvls)`

Traceback (most recent call last):
  File "mimc_run.py", line 144, in <module>
    fnInit=run.initRun)# initialize the run
  File "/home/hammouc/Dropbox/Smoothing_project/code/mimclib/mimclib/test.py", line 104, in RunStandardTest
    mimcRun.doRun()
  File "/home/hammouc/Dropbox/Smoothing_project/code/mimclib/mimclib/mimc.py", line 858, in doRun
    newTodoM = self._extendLevels()
  File "/home/hammouc/Dropbox/Smoothing_project/code/mimclib/mimclib/mimc.py", line 717, in _extendLevels
    self.fn.ExtendLvls(lvls=self.last_itr.get_lvls())
  File "mimc_run.py", line 53, in <lambda>
    run.setFunctions(ExtendLvls=lambda lvls, r=run: self.extendLvls(run, lvls))
  File "mimc_run.py", line 92, in extendLvls
    lev2knots=lambda beta:misc.lev2knots_doubling(beta+1))
  File "/home/hammouc/Dropbox/Smoothing_project/code/mimclib/mimclib/misc.py", line 384, in estimate_misc_error_rates
    mat[:, d:] = lev2knots(mat[:, d:]-1) 
  File "mimc_run.py", line 92, in <lambda>
    lev2knots=lambda beta:misc.lev2knots_doubling(beta+1))
  File "/home/hammouc/Dropbox/Smoothing_project/code/mimclib/mimclib/misc.py", line 343, in lev2knots_doubling
    m= 2 ** (i-1)+1 
ValueError: Integers to negative integer powers are not allowed.

Do you have any idea if I am doing something wrong or I need to change something in the misc code? Thanks.

**Comment by hammouc** [comment]
This may be due to python compiler. One solution to overcome this is to change the method lev2knots_doubling as below

` def lev2knots_doubling(i):

    i = np.array([i] if np.isscalar(i) else i, dtype=np.int)
    m= 2 ** (i-1.0)+1
    m=m.astype(np.int)
    m[i==1] = 1
    m[i==0] = 0
    return m`
