### ISSUE TITLE
Error in  ./plot_data.py -db_tag CEM

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#24]
kw13919:litvina~/MIMCLIB/mimclib/tests> ./plot_data.py -db_tag CEM
Traceback (most recent call last):
  File "./plot_data.py", line 54, in <module>
    main()
  File "./plot_data.py", line 45, in main
    run_data = db.readRuns(db.getRunsIDs(tag=args.db_tag, done_flag=1))
  File "/home/litvina/MIMCLIB/mimclib/mimclib/db.py", line 299, in getRunsIDs
    ids = self._fetchArray(query, params)
  File "/home/litvina/MIMCLIB/mimclib/mimclib/db.py", line 263, in _fetchArray
    dataAll = cur.execute(query, params if params else [])
  File "/home/litvina/MIMCLIB/mimclib/mimclib/db.py", line 49, in execute
    self.cur.execute(query, tuple(params))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND tag LIKE 'CEM'  ORDER BY tag, dim,\n        TOL' at line 1")
kw13919:litvina~/MIMCLIB/mimclib/tests>

**Comment by haji-ali** [comment]
Did this get fix after we updated MySQLdb? If so please close the issue
