### ISSUE TITLE
If I try to plot results using a ssh remote terminal

### ISSUE THREAD

**Issue by pvilanova** [StochasticNumerics/mimclib#31]
I got this error:

Traceback (most recent call last):
  File "./plot_data.py", line 54, in <module>
    main()
  File "./plot_data.py", line 50, in main
    miplot.genPDFBooklet(run_data, fileName=args.o, exact=args.qoi_exact)
  File "/home/pv/mimclib/mimclib/plot.py", line 537, in genPDFBooklet
    ax = add_fig()
  File "/home/pv/mimclib/mimclib/plot.py", line 534, in add_fig
    figures.append(plt.figure())
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423, in figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 87, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by Virtakuono** [comment]
Are you on SSH ?

**Comment by pvilanova** [comment]
Solved. thanks.
