### ISSUE TITLE
Problems in the curtosis plots

### ISSUE THREAD

**Issue by Virtakuono** [StochasticNumerics/mimclib#32]
When running the GBM example with "-mimc_moments 4" I have the following crash.

Traceback (most recent call last):
  File "run.py", line 68, in <module>
    fnAddExtraArgs=addExtraArguments)
  File "/home/jhappola/mimclib/mimclib/test.py", line 82, in RunStandardTest
    mimcRun.doRun()
  File "/home/jhappola/mimclib/mimclib/mimc.py", line 600, in doRun
    newTodoM)), verbose)
  File "/home/jhappola/mimclib/mimclib/mimc.py", line 536, in _genSamples
    self.data.addSamples(psums, M, t)
  File "/home/jhappola/mimclib/mimclib/mimc.py", line 144, in addSamples
    self.psums += psums
ValueError: operands could not be broadcast together with shapes (3,4) (3,2) (3,4) 

J

**Comment by haji-ali** [comment]
Fixed. Please pull the changes.

**Comment by Virtakuono** [comment]
One step closer, but not quite there.

-----------------------------------------------------
Traceback (most recent call last):
  File "/home/jhappola/mimclib/mimclib/plot.py", line 712, in genPDFBooklet
    direction=direction)
  File "/home/jhappola/mimclib/mimclib/plot.py", line 369, in plotSkewnessVsLvls
    E3l = central_moments[:, 2]
IndexError: index 2 is out of bounds for axis 1 with size 2
-----------------------------------------------------
-----------------------------------------------------
Traceback (most recent call last):
  File "/home/jhappola/mimclib/mimclib/plot.py", line 712, in genPDFBooklet
    direction=direction)
  File "/home/jhappola/mimclib/mimclib/plot.py", line 345, in plotKurtosisVsLvls
    E4l = central_moments[:, 3]
IndexError: index 3 is out of bounds for axis 1 with size 2
-----------------------------------------------------

**Comment by haji-ali** [comment]
Fair enough. Fixed.

**Comment by Virtakuono** [comment]
Ok, now it ran through. Pics will follow shortly.
