### ISSUE TITLE
RuntimeError: Invalid DISPLAY variable plot_data.py

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#35]
I tried from home via ssh

kw13919:litvina~/MIMCLIB/mimclib/tests> ./plot_data.py  -db_tag CEM_18 -o 13Apr.pdf
Traceback (most recent call last):
  File "./plot_data.py", line 60, in <module>
    main()
  File "./plot_data.py", line 56, in main
    miplot.genPDFBooklet(run_data, fileName=args.o, exact=args.qoi_exact)
  File "/home/litvina/MIMCLIB/mimclib/mimclib/plot.py", line 629, in genPDFBooklet
    ax = add_fig()
  File "/home/litvina/MIMCLIB/mimclib/mimclib/plot.py", line 626, in add_fig
    figures.append(plt.figure())
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
kw13919:litvina~/MIMCLIB/mimclib/tests> ./plot_data.py  -db_tag CEM_18 -o 13Apr.pdf

Please advise

**Comment by haji-ali** [comment]
Run
`> export DISPLAY=:0`

**Comment by litvinen** [comment]
Thanks, option "-X" also helped
 ssh -X litvina@10.68.170.9
