### ISSUE TITLE
TypeError: <lambda>() got an unexpected keyword argument 'iteration_idx'

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#51]
kw13919:litvina~/MIMCLIB/mimclib/tests/CEM> ./echo_test_cmd_alex.py -multi True | parallel -j10
Traceback (most recent call last):
  File "run.py", line 71, in <module>
    fnSeed=seedRandomGen)
  File "/home/litvina/MIMCLIB/mimclib/mimclib/test.py", line 78, in RunStandardTest
    mimcRun.doRun()
  File "/home/litvina/MIMCLIB/mimclib/mimclib/mimc.py", line 675, in doRun
    self.fnItrDone(iteration_idx=itrIndex, TOL=TOL, totalTime=totalTime)
TypeError: <lambda>() got an unexpected keyword argument 'iteration_idx'

[1]+  Stopped                 ./echo_test_cmd_alex.py -multi True | parallel -j10

+++++++++++++ 
Similar error in  /gbm
kw13919:litvina~/MIMCLIB/mimclib/tests/gbm> ./echo_test_cmd.py -multi True | parallel -j2
Traceback (most recent call last):
  File "mimc_run.py", line 87, in <module>
    fnAddExtraArgs=addExtraArguments)
  File "/home/litvina/MIMCLIB/mimclib/mimclib/test.py", line 78, in RunStandardTest
    mimcRun.doRun()
  File "/home/litvina/MIMCLIB/mimclib/mimclib/mimc.py", line 675, in doRun
    self.fnItrDone(iteration_idx=itrIndex, TOL=TOL, totalTime=totalTime)
TypeError: <lambda>() got an unexpected keyword argument 'iteration_idx'
Traceback (most recent call last):
  File "mimc_run.py", line 87, in <module>
    fnAddExtraArgs=addExtraArguments)
  File "/home/litvina/MIMCLIB/mimclib/mimclib/test.py", line 78, in RunStandardTest
    mimcRun.doRun()
  File "/home/litvina/MIMCLIB/mimclib/mimclib/mimc.py", line 675, in doRun
    self.fnItrDone(iteration_idx=itrIndex, TOL=TOL, totalTime=totalTime)
TypeError: <lambda>() got an unexpected keyword argument 'iteration_idx'
Traceback (most recent call last):

**Comment by litvinen** [comment]
I pulled the latest version from github, compiled it, I updated the data base, but it didn't help

**Comment by litvinen** [comment]
The issue is resolved. I created a new directory, cloned the code from github, compiled and it is working.
I do not know what was the reason.
