### ISSUE TITLE
ImportError: No module named dill

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#60]
kw13919:litvina~/NEWMIMCLIB/mimclib/tests> ./plot_prog.py -db_tag CEM1 -o CEM1.pdf
Traceback (most recent call last):
  File "./plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1326, in run_program
    run_data = db.readRuns(tag=args.db_tag, done_flag=args.done_flag)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/db.py", line 472, in readRuns
    return self.readRunsByID(runs_ids)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/db.py", line 363, in readRunsByID
    import dill
ImportError: No module named dill
kw13919:litvina~/NEWMIMCLIB/mimclib/tests> 

But I have already dill
kw13919:litvina~/NEWMIMCLIB/mimclib/tests> pip install dillRequirement already satisfied (use --upgrade to upgrade): dill in /home/litvina/anaconda2/lib/python2.7/site-packages

What I am doing wrong?

**Comment by litvinen** [comment]
Problem is partially solved by
sudo pip install dill
But then I received the next error
w13919:litvina~/NEWMIMCLIB/mimclib/tests> ./plot_prog.py -db_tag CEM1 -o CEM1.pdf
Estimated exact value is 8.32800482281138
-----------------------------------------------------
Traceback (most recent call last):
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1062, in genPDFBooklet
    Ref_kwargs={'ls': '--', 'c':'k', 'label': '{rate:.2g}'})
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 462, in plotWorkVsMaxError
    **Ref_kwargs)))
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 66, in ExpLine
    assert data is not None and len(data) > 0, "rate or data must be given"
AssertionError: rate or data must be given
-----------------------------------------------------
Traceback (most recent call last):
  File "./plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1336, in run_program
    else filteritr_convergent)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1064, in genPDFBooklet
    __plot_except(ax)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1062, in genPDFBooklet
    Ref_kwargs={'ls': '--', 'c':'k', 'label': '{rate:.2g}'})
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 462, in plotWorkVsMaxError
    **Ref_kwargs)))
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 66, in ExpLine
    assert data is not None and len(data) > 0, "rate or data must be given"
AssertionError: rate or data must be given
kw13919:litvina~/NEWMIMCLIB/mimclib/tests>
