### ISSUE TITLE
Problem woith plot: AssertionError: rate or data must be given

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#61]
kw13919:litvina~/NEWMIMCLIB/mimclib/tests> ./plot_prog.py -db_tag CEM1 -o CEM1.pdf
Estimated exact value is 8.32800482281138
-----------------------------------------------------
Traceback (most recent call last):
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1062, in genPDFBooklet
    Ref_kwargs={'ls': '--', 'c':'k', 'label': '{rate:.2g}'})
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 462, in plotWorkVsMaxError
    **Ref_kwargs)))
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 66, in ExpLine
    assert data is not None and len(data) > 0, "rate or data must be given"
AssertionError: rate or data must be given
-----------------------------------------------------
Traceback (most recent call last):
  File "./plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1336, in run_program
    else filteritr_convergent)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1064, in genPDFBooklet
    __plot_except(ax)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1062, in genPDFBooklet
    Ref_kwargs={'ls': '--', 'c':'k', 'label': '{rate:.2g}'})
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 462, in plotWorkVsMaxError
    **Ref_kwargs)))
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 66, in ExpLine
    assert data is not None and len(data) > 0, "rate or data must be given"
AssertionError: rate or data must be given
kw13919:litvina~/NEWMIMCLIB/mimclib/tests>

**Comment by haji-ali** [comment]
It is difficult for me to regenerate this error without your data.
If you pull the changes now and try again, the plots will appear and this particular plot will fail, but this might allow me to understand the particular problem.

**Comment by litvinen** [comment]
May be because I computed only one TOL

**Comment by haji-ali** [comment]
No, it should not be a problem

**Comment by litvinen** [comment]
I pulled new changes.
kw13919:litvina~/NEWMIMCLIB/mimclib/tests> ./plot_prog.py -db_tag CEM1 -o p1.pdf
Estimated exact value is 8.32800482281138
polynomial.py:594: (RankWarning) Polyfit may be poorly conditioned
polynomial.py:594: (RankWarning) Polyfit may be poorly conditioned

And I can see graphics! Thanks
