### ISSUE TITLE
Can vizualize particle-example results

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#63]
kw13919:litvina~/NEWMIMCLIB/mimclib2/tests> ./plot_prog.py -db_tag particle_1 -o p1.pdf
Estimated exact value is 0.93093089520198
-----------------------------------------------------
Traceback (most recent call last):
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1245, in genPDFBooklet
    plotThetaRefVsTOL(ax, runs, filteritr=filteritr, eta=eta, chi=chi, fmt='--k')
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 881, in plotThetaRefVsTOL
    for _, itr in enum_iter(runs, filteritr)])
NameError: global name 'r' is not defined
-----------------------------------------------------
Traceback (most recent call last):
  File "./plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1336, in run_program
    else filteritr_convergent)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1247, in genPDFBooklet
    __plot_except(ax)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1245, in genPDFBooklet
    plotThetaRefVsTOL(ax, runs, filteritr=filteritr, eta=eta, chi=chi, fmt='--k')
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 881, in plotThetaRefVsTOL
    for _, itr in enum_iter(runs, filteritr)])
NameError: global name 'r' is not defined
kw13919:litvina~/NEWMIMCLIB/mimclib2/tests>

**Comment by haji-ali** [comment]
This should have been resolved if you have pulled the latest version (1.0.2.dev1)
