### ISSUE TITLE
/test/matern example

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#65]
Error messages
kw13919:litvina~/NEWMIMCLIB/mimclib/tests/matern> ./plot_example 
Plotting misc_matern_d1_nu3.5
Plotting misc_matern_d1_nu2.5
Plotting misc_matern_d1_nu1.0
Plotting misc_matern_d1_nu1.5
Plotting misc_matern_d1_nu50
Plotting misc_matern_d3_nu4.5
Plotting misc_matern_d3_nu50
Plotting misc_matern_d3_nu3
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
    raise Exception("No runs!!!")
Exception: No runs!!!
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
    raise Exception("No runs!!!")
Exception: No runs!!!
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
    raise Exception("No runs!!!")
Exception: No runs!!!
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
    raise Exception("No runs!!!")
Exception: No runs!!!
Traceback (most recent call last):
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
  File "../plot_prog.py", line 4, in <module>
        run_program()
run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
        raise Exception("No runs!!!")
raise Exception("No runs!!!")
ExceptionException: No runs!!!: 
No runs!!!
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
    raise Exception("No runs!!!")
Exception: No runs!!!
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
    raise Exception("No runs!!!")
Exception: No runs!!!
kw13919:litvina~/NEWMIMCLIB/mimclib/tests/matern>

**Comment by haji-ali** [comment]
Did you run the matern example?

**Comment by litvinen** [comment]
Yes, I have sent you output via email
I run again and received similar
kw13919:litvina~/NEWMIMCLIB/mimclib/tests/matern> ./plot_example 
Plotting misc_matern_d1_nu3.5
Plotting misc_matern_d1_nu2.5
Plotting misc_matern_d1_nu1.0
Plotting misc_matern_d1_nu1.5
Plotting misc_matern_d1_nu50
Plotting misc_matern_d3_nu4.5
Plotting misc_matern_d3_nu50
Plotting misc_matern_d3_nu3
Traceback (most recent call last):
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
  File "../plot_prog.py", line 4, in <module>
        run_program()
run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
        raise Exception("No runs!!!")
raise Exception("No runs!!!")
Exception: ExceptionNo runs!!!: No runs!!!

Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
    raise Exception("No runs!!!")
Exception: No runs!!!
    raise Exception("No runs!!!")
Exception: No runs!!!
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
        run_program()
raise Exception("No runs!!!")
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
Exception: No runs!!!
    raise Exception("No runs!!!")
Exception: No runs!!!
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
    raise Exception("No runs!!!")
Exception: No runs!!!
Traceback (most recent call last):
  File "../plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1327, in run_program
    raise Exception("No runs!!!")
Exception: No runs!!!
kw13919:litvina~/NEWMIMCLIB/mimclib/tests/matern>
