### ISSUE TITLE
Can not visualize

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#70]
I have the latest version and obtain
kw13919:litvina~/NEWMIMCLIB/mimclib/tests> ./plot_prog.py -db_tag Oct13_cmlmc3_large1 -o 3.pdf
Estimated exact value is 6.52591973382019
Traceback (most recent call last):
  File "./plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1367, in run_program
    else filteritr_convergent)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1254, in genPDFBooklet
    line_data, _ = plotLvlsNumVsTOL(ax, runs, filteritr=filteritr)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 860, in plotLvlsNumVsTOL
    ipdb.embed()

In [1]:

**Comment by haji-ali** [comment]
Sorry, it's a debug command that I forgot to remove. Please pull the changes again.
