### ISSUE TITLE
Problems with python

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#80]
kw13919:litvina~/NEWMIMCLIB/mimclib3/tests/gbm> ./echo_test_cmd.py 
python mimc_run.py -mimc_TOL 0.001 -mimc_max_TOL 0.5      -qoi_sigma 0.1 -qoi_mu 1 -qoi_seed 0 -mimc_moments 4 -mimc_M0 100     -mimc_min_dim 1 -mimc_w 1 -mimc_s 1 -mimc_gamma 1 -mimc_beta 2     -mimc_confidence 0.95 -mimc_theta 0.5 -mimc_bayes_fit_lvls 5     -mimc_bayes_k1 0.01 -mimc_reuse_samples True  -mimc_bayesian False -mimc_theta 0.5  -mimc_verbose 10 -db False -db_tag GBM_testcase 
kw13919:litvina~/NEWMIMCLIB/mimclib3/tests/gbm> python mimc_run.py -mimc_TOL 0.001 -mimc_max_TOL 0.5      -qoi_sigma 0.1 -qoi_mu 1 -qoi_seed 0 -mimc_moments 4 -mimc_M0 100     -mimc_min_dim 1 -mimc_w 1 -mimc_s 1 -mimc_gamma 1 -mimc_beta 2     -mimc_confidence 0.95 -mimc_theta 0.5 -mimc_bayes_fit_lvls 5     -mimc_bayes_k1 0.01 -mimc_reuse_samples True  -mimc_bayesian False -mimc_theta 0.5  -mimc_verbose 10 -db False -db_tag GBM_testcase
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "mimc_run.py", line 71, in <module>
    import mimclib
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/**init**.py", line 4, in <module>
    from . import plot
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 6, in <module>
    import matplotlib.pylab as plt
  File "/home/litvina/.local/lib/python2.7/site-packages/matplotlib/pylab.py", line 231, in <module>
    import matplotlib.finance
  File "/home/litvina/.local/lib/python2.7/site-packages/matplotlib/finance.py", line 25, in <module>
    from matplotlib.dates import date2num
  File "/home/litvina/.local/lib/python2.7/site-packages/matplotlib/dates.py", line 137, in <module>
    import matplotlib.ticker as ticker
  File "/home/litvina/.local/lib/python2.7/site-packages/matplotlib/ticker.py", line 163, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/litvina/.local/lib/python2.7/site-packages/matplotlib/transforms.py", line 39, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ImportError: numpy.core.multiarray failed to import
kw13919:litvina~/NEWMIMCLIB/mimclib3/tests/gbm>

**Comment by litvinen** [comment]
pip install -U numpy 
solves the problem (taken from here http://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import )
