### ISSUE TITLE
Error in ./plot_prog.py

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#83]
kw13919:litvina~/NEWMIMCLIB/mimclib3/tests> ./plot_prog.py -db_tag Oct19AAA_cmlmc3_1 -o Oct19AAA_cmlmc3.pdf
Traceback (most recent call last):
  File "./plot_prog.py", line 4, in <module>
    run_program()
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1364, in run_program
    else filteritr_convergent)
  File "/home/litvina/.local/lib/python2.7/site-packages/mimclib/plot.py", line 1033, in genPDFBooklet
    maxTOL = np.max([r.db_data.finalTOL for r in runs])
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2258, in amax
    out=out, keepdims=keepdims)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
kw13919:litvina~/NEWMIMCLIB/mimclib3/tests>prog.py

**Comment by litvinen** [comment]
Probably because the list of results is empty (computations are still going). But a more "human" message would be more appreciated.

**Comment by haji-ali** [comment]
Noted
