### ISSUE TITLE
Installation problem on Mac 10.11.16

### ISSUE THREAD

**Issue by anamika168** [StochasticNumerics/mimclib#97]
kl-17316:mimclib pandeya$ make pip
pip install --user -e .[mysqldb]
Obtaining file:///Users/pandeya/git/mimclib
Collecting MySQL-python (from mimclib==1.0.2.dev4)
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fg/gb2h76k12qg8v_0f51l7_1q9sxxc_0/T/pip-build-BongRD/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fg/gb2h76k12qg8v_0f51l7_1q9sxxc_0/T/pip-build-BongRD/MySQL-python/
make: *** [pip] Error 1

just for your information, python version is
Python 2.7.10
and pip version is
pip 9.0.1

**Comment by anamika168** [comment]
I have solved this step by myself and got the message 
Successfully installed mimclib-1.0.2.dev4
